// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-9WiTo_Mz4zm4wl1d9OzDMNYuXyRoPQ',
    appId: '1:329544232036:web:c9f1dd350cff7e1cb08371',
    messagingSenderId: '329544232036',
    projectId: 'todo-app-3d537',
    authDomain: 'todo-app-3d537.firebaseapp.com',
    storageBucket: 'todo-app-3d537.firebasestorage.app',
    measurementId: 'G-CWFQ0FDVE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFyANCf0wvo20z2u0Di4juGLvQZRB9MBQ',
    appId: '1:329544232036:android:9aa0ee84ca8c4ff9b08371',
    messagingSenderId: '329544232036',
    projectId: 'todo-app-3d537',
    storageBucket: 'todo-app-3d537.firebasestorage.app',
  );
}
